/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StrapsSlugRouteImport } from './routes/straps.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PoliciesTermsRouteImport } from './routes/policies.terms'
import { Route as PoliciesRefundRouteImport } from './routes/policies.refund'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies.privacy'
import { Route as PoliciesLegalRouteImport } from './routes/policies.legal'
import { Route as PoliciesDeliveryRouteImport } from './routes/policies.delivery'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrapsSlugRoute = StrapsSlugRouteImport.update({
  id: '/straps/$slug',
  path: '/straps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/policies/terms',
  path: '/policies/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRefundRoute = PoliciesRefundRouteImport.update({
  id: '/policies/refund',
  path: '/policies/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/policies/privacy',
  path: '/policies/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesLegalRoute = PoliciesLegalRouteImport.update({
  id: '/policies/legal',
  path: '/policies/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesDeliveryRoute = PoliciesDeliveryRouteImport.update({
  id: '/policies/delivery',
  path: '/policies/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/policies/delivery': typeof PoliciesDeliveryRoute
  '/policies/legal': typeof PoliciesLegalRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/straps/$slug': typeof StrapsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/policies/delivery': typeof PoliciesDeliveryRoute
  '/policies/legal': typeof PoliciesLegalRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/straps/$slug': typeof StrapsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/policies/delivery': typeof PoliciesDeliveryRoute
  '/policies/legal': typeof PoliciesLegalRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/refund': typeof PoliciesRefundRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/straps/$slug': typeof StrapsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/policies/delivery'
    | '/policies/legal'
    | '/policies/privacy'
    | '/policies/refund'
    | '/policies/terms'
    | '/products/$slug'
    | '/straps/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/policies/delivery'
    | '/policies/legal'
    | '/policies/privacy'
    | '/policies/refund'
    | '/policies/terms'
    | '/products/$slug'
    | '/straps/$slug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/policies/delivery'
    | '/policies/legal'
    | '/policies/privacy'
    | '/policies/refund'
    | '/policies/terms'
    | '/products/$slug'
    | '/straps/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  PoliciesDeliveryRoute: typeof PoliciesDeliveryRoute
  PoliciesLegalRoute: typeof PoliciesLegalRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesRefundRoute: typeof PoliciesRefundRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  StrapsSlugRoute: typeof StrapsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/straps/$slug': {
      id: '/straps/$slug'
      path: '/straps/$slug'
      fullPath: '/straps/$slug'
      preLoaderRoute: typeof StrapsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/policies/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/refund': {
      id: '/policies/refund'
      path: '/policies/refund'
      fullPath: '/policies/refund'
      preLoaderRoute: typeof PoliciesRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/legal': {
      id: '/policies/legal'
      path: '/policies/legal'
      fullPath: '/policies/legal'
      preLoaderRoute: typeof PoliciesLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/delivery': {
      id: '/policies/delivery'
      path: '/policies/delivery'
      fullPath: '/policies/delivery'
      preLoaderRoute: typeof PoliciesDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  PoliciesDeliveryRoute: PoliciesDeliveryRoute,
  PoliciesLegalRoute: PoliciesLegalRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesRefundRoute: PoliciesRefundRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  StrapsSlugRoute: StrapsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
